### ISSUE TITLE
EM Processing Unit (PU) powers up but does not boot

### ISSUE THREAD

**Issue by kjerram** [oceanmapping/community#18]
Context: EM2040 testing with a portable processing unit (PPU) in an autonomous vessel.

Symptoms:
1. The portable processing unit (PPU) would power up but not boot.
2. The screen showed 'Power On' but no other information, and SIS / K-Controller would not connect.
3. Waiting 10-15 minutes and multiple restarts (via relay, not the PPU power button) did not resolve the issue.

**Comment by kjerram** [comment]
Solution from Kongsberg technical support for PU / PPU:

1. Power down.
2. Unplug ALL sensors and restart the PPU with nothing else connected.
3. (In this case, the PPU booted properly with no sensors connected.)
4. Power down.
5. Plug all sensors back in to the PPU and restart.
6. (In this case, the PPU booted properly with all sensors connected.)

The technical support included two other suggestions:
1. If the process above did not fix the problem, the next step would be removing the PPU and reseating all boards.
2. It's possible that power cycling with an external relay (in the autonomous vehicle) is having a different effect than power cycling with the PPU power button directly.  (While the vessel was opened up, power was cycled using the power button.)

**Comment by valschmidt** [comment]
What do you think is failing here? Do you have any other symptoms? 

Is it correct that the PPU powers on (LEDs light) but the CPU in the PU does not fully boot? 
Could you telnet into the PPU in this state? 
Could you ping it? 
Was there a link light between the survey PC and the PPU? 
When a manufacturer suggests unplugging everything, I always like to ask what this is meant to fix. Is the idea that there is some short in the peripheral systems? Do we need to try to track that down now if that fixed the problem? 

The fact that this problem did not occur during DriX-8 commissioning in 2021, a week of trials in October/November, 10 days in March or 3 weeks in May is interesting (if not confusing). 

Could this be related to heat? We had some hot days in May and saw pretty warm temperatures in the electronics compartment at times. But we didn't see any adverse affects to the systems. 

It can be difficult to discern if the problem is the EM2040 or the system supplying its power.  One can consume months going back and forth with the manufacturer trying to sort it out. Would it have been helpful to have monitored the voltage / current of the DriX power supply during PPU startup and see if there is some brown-out that occurs when the PPU is powered on initially? One could compare this with the button push. Was there any effort to temporarily power the PPU from another source?

Always good to know how to fix a problem. Harder to understand what caused the problem and how to prevent it.
